import { Navigate, Route, Routes } from 'react-router-dom'
import { DashboardLayout } from './components/layout/DashboardLayout'
import { AuthGuard } from './components/auth-guard'
import { useAuth } from './context/auth-context'
import { AuthCallbackPage } from './pages/auth-callback-page'
import { LoginPage } from './pages/login-page'
import { RegisterPage } from './pages/register-page'
import Dashboard from './pages/Dashboard'
import Transactions from './pages/Transactions'
import Wallets from './pages/Wallets'
import Budgets from './pages/Budgets'
import Groups from './pages/Groups'
import Settings from './pages/Settings'
import NotFound from './pages/not-found'

import { InvitePage } from './pages/InvitePage'
import { SelectGroupPage } from './pages/SelectGroupPage'
